### ISSUE TITLE
request for model_weights/salgan_salicon.pt file

### ISSUE THREAD

**Issue by prashnani** [Linardos/SalEMA#9]
Hi, thanks for releasing the source code for your work!

Could you please also release the salgan_salicon.pt file mentioned in [line 33](https://github.com/Linardos/SalEMA/blob/master/src/train.py#L33) of train.py? 

Thanks,
Ekta

**Comment by Linardos** [comment]
Sadly, I no longer work for the same institute and no longer have access to the weights. However, they are the same as the ones found in this website: https://imatge-upc.github.io/salgan/ (Look for the SalGAN generator weights link). The catch is you might have to transfer them to PyTorch first as the original model was implemented in Theano if my memory serves me right.
